version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://sindhufin0820:4toCXLcrxsICRU83@cluster0.macce.mongodb.net/fitnics
      - MICROSERVICE_URL=http://microservice:8000
    depends_on:
      - microservice
    networks:
      - fitnics-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - backend
    networks:
      - fitnics-network

  microservice:
    build: ./microservice
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb+srv://sindhufin0820:4toCXLcrxsICRU83@cluster0.macce.mongodb.net/fitnics
    networks:
      - fitnics-network

networks:
  fitnics-network:
    driver: bridge

volumes:
  mongo-data: 